version: "3.8"
services:
  csharp: #docker run -it -v ${PWD}:/work -w /work -p 5000:5000 csharp
    container_name: csharp
    build:
      context: ./cs
    ports:
      - 5000:5000
  golang: #docker run -it -v ${PWD}:/work -w /work -p 5001:5000 golang:1.0.0
    container_name: golang
    build: 
      context: ./golang
    ports:
      - 5001:5000
  nodejs: #docker run -it -v ${PWD}:/work -w /work -p 5002:5000 nodejs:1.0.0
    container_name: nodejs
    build:
      context: ./nodejs
    ports:
      - 5002:5000
  python: #docker run -it -v ${PWD}:/work -w /work -p 5003:5000 python:1.0.0
    container_name: python
    build:
      context: ./python
    ports:
      - 5003:5000
